CREATE TABLE IF NOT EXISTS mpa (
    id INTEGER PRIMARY KEY,
    name VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS genres (
    id INTEGER PRIMARY KEY,
    name VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS friend_status (
    id INTEGER PRIMARY KEY,
    name VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    login VARCHAR(100) NOT NULL,
    name VARCHAR(255),
    birthday DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS films (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(200),
    release_date DATE NOT NULL,
    duration INTEGER NOT NULL,
    mpa_id INTEGER NOT NULL,
    CONSTRAINT fk_film_mpa
        FOREIGN KEY (mpa_id)
        REFERENCES mpa(id)
);

CREATE TABLE IF NOT EXISTS friends (
    user_id BIGINT NOT NULL,
    friend_id BIGINT NOT NULL,
    status_id INTEGER NOT NULL,

    PRIMARY KEY (user_id, friend_id),

    CONSTRAINT fk_friend_user
        FOREIGN KEY (user_id)
        REFERENCES users(id),

    CONSTRAINT fk_friend_friend
        FOREIGN KEY (friend_id)
        REFERENCES users(id),

    CONSTRAINT fk_friend_status
        FOREIGN KEY (status_id)
        REFERENCES friend_status(id)
);

CREATE TABLE IF NOT EXISTS likes (
    film_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,

    PRIMARY KEY (film_id, user_id),

    CONSTRAINT fk_like_film
        FOREIGN KEY (film_id)
        REFERENCES films(id),

    CONSTRAINT fk_like_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS film_genres (
    film_id BIGINT NOT NULL,
    genre_id INTEGER NOT NULL,

    PRIMARY KEY (film_id, genre_id),

    CONSTRAINT fk_fg_film
        FOREIGN KEY (film_id)
        REFERENCES films(id),

    CONSTRAINT fk_fg_genre
        FOREIGN KEY (genre_id)
        REFERENCES genres(id)
);

CREATE TABLE IF NOT EXISTS events (
    event_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    event_type VARCHAR(10) NOT NULL,
    operation VARCHAR(10) NOT NULL,
    entity_id BIGINT NOT NULL,

    CONSTRAINT fk_event_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content TEXT NOT NULL,
    is_positive BOOLEAN,
    user_id BIGINT NOT NULL,
    film_id BIGINT NOT NULL,
    CONSTRAINT fk_reviews_user
        FOREIGN KEY(user_id) REFERENCES users(id),
    CONSTRAINT fk_reviews_film
        FOREIGN KEY(film_id) REFERENCES films(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS reviews_evaluation (
    review_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    review_evaluation BOOLEAN NOT NULL,
    PRIMARY KEY(review_id, user_id),
    CONSTRAINT fk_evaluation_review
        FOREIGN KEY(review_id) REFERENCES reviews(id) ON DELETE CASCADE,
    CONSTRAINT fk_evaluation_user
        FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
);